baseURL = "https://docs.joinmastodon.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Mastodon documentation"
paginate = 100
enableGitInfo = true
disablePathToLower = true
theme = "hextra"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[markup.goldmark.renderer]
unsafe = true

###

[languages.en]
contentDir = "content/en"
languageName = "English"
weight = -99

[languages.pl]
contentDir = "content/pl"
languageName = "Polski"
weight = 0

[languages.zh-cn]
contentDir = "content/zh-cn"
languageName = "简体中文"
weight = 1

[languages.ja]
contentDir = "content/ja"
languageName = "日本語"
weight = 2

###

[[menu.main]]
name = "Search"
weight = -99
[menu.main.params]
type = "search"

[[menu.main]]
name = "Join Mastodon"
url = "https://joinmastodon.org"
weight = 1

[[menu.main]]
name = "Read our blog"
url = "https://blog.joinmastodon.org"
weight = 2

[[menu.main]]
name = "Github"
url = "https://github.com/mastodon/mastodon"
weight = 3
[menu.main.params]
icon = "github"

###

[params.editURL]
enable = true
base = "https://github.com/mastodon/documentation/edit/main"

[params.navbar]
displayTitle = false
displayLogo = true
[params.navbar.logo]
path = "branding/wordmark-black-text.svg"
dark = "branding/wordmark-white-text.svg"
link = "/"
height = "22px"
width = "85px"

[params.page]
width = "wide"

[params.search]
enable = true
type = "flexsearch"
[params.search.flexsearch]
index = "content"